/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.awesome.micronaut;

import io.micronaut.context.ApplicationContext; 

public class App {

    public static void main(String[] args) {
        ApplicationContext applicationContext = ApplicationContext.run();

        var dependency = applicationContext.getBean(SomeDependency.class);

        dependency.doStuff();

        dependency.publishEvent();

        dependency.consumeConfiguration();
    }
}
