/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.awesome.micronaut;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appShouldNotBeNull() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should not be null");
    }
}
